<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="5" passed="3">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="292" started-at="2021-03-19T22:01:06 IST" finished-at="2021-03-19T22:01:06 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="292" started-at="2021-03-19T22:01:06 IST" finished-at="2021-03-19T22:01:06 IST">
      <class name="CRUDValidation.DBvalidation">
        <test-method status="PASS" signature="setUp()[pri:0, instance:CRUDValidation.DBvalidation@396f6598]" name="setUp" is-config="true" duration-ms="234" started-at="2021-03-19T22:01:06 IST" finished-at="2021-03-19T22:01:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="Create()[pri:0, instance:CRUDValidation.DBvalidation@396f6598]" name="Create" duration-ms="7" started-at="2021-03-19T22:01:06 IST" finished-at="2021-03-19T22:01:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Create -->
        <test-method status="FAIL" signature="Delete()[pri:0, instance:CRUDValidation.DBvalidation@396f6598]" name="Delete" duration-ms="2" started-at="2021-03-19T22:01:06 IST" finished-at="2021-03-19T22:01:06 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at CRUDValidation.DBvalidation.Delete(DBvalidation.java:151)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Delete -->
        <test-method status="PASS" signature="Insert()[pri:0, instance:CRUDValidation.DBvalidation@396f6598]" name="Insert" duration-ms="7" started-at="2021-03-19T22:01:06 IST" finished-at="2021-03-19T22:01:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Insert -->
        <test-method status="PASS" signature="Read()[pri:0, instance:CRUDValidation.DBvalidation@396f6598]" name="Read" duration-ms="9" started-at="2021-03-19T22:01:06 IST" finished-at="2021-03-19T22:01:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Read -->
        <test-method status="FAIL" signature="Update()[pri:0, instance:CRUDValidation.DBvalidation@396f6598]" name="Update" duration-ms="1" started-at="2021-03-19T22:01:06 IST" finished-at="2021-03-19T22:01:06 IST">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at CRUDValidation.DBvalidation.Update(DBvalidation.java:125)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Update -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:CRUDValidation.DBvalidation@396f6598]" name="tearDown" is-config="true" duration-ms="0" started-at="2021-03-19T22:01:06 IST" finished-at="2021-03-19T22:01:06 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- CRUDValidation.DBvalidation -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
